### ISSUE TITLE
Allow users to cancel upload with ESC

### ISSUE THREAD

**Issue by hanzei** [streamer45/mattermost-plugin-screen#4]
A user might change his mind and want to cancel an upload. Allow this via `ESC`.

**Comment by streamer45** [comment]
Should be now implemented by https://github.com/streamer45/mattermost-plugin-screen/commit/6b86045ed59948c205dbd6b176a85c89a0855e84.

**Comment by jprusch** [comment]
Sehr geehrte Damen und Herren,
ich bin vom 8.6. bis zum 12.6. nicht im Hause und habe daher leider keinen Zugriff auf meine E-Mails.
Ihre Mail wird NICHT weitergeleitet und nach meiner Rückkehr bearbeitet.
In dringende Fällen wenden Sie sich bitte an Hr. Tarrach (v.tarrach@schaeferbarthold.de)
Mit freundlichen Grüßen

i.V. Jan-Peter Rusch

TEL +49 (0)571-502-145 | FAX +49 (0)571-502-66-145
j.rusch@schaeferbarthold.de
______________________________________________________________________
Schäferbarthold GmbH
Erbeweg 2-12 | 32457 Porta Westfalica | Deutschland
www.schaeferbarthold.de
Schäferbarthold GmbH: Amtsgericht Bad Oeynhausen HRB 3748
Geschäftsführer: Dr. Volker Schäferbarthold, Dr. Christian Schäferbarthold, Wolfgang Schäferbarthold
Should be now implemented by https://github.com/streamer45/mattermost-plugin-screen/commit/6b86045ed59948c205dbd6b176a85c89a0855e84.

**Comment by hanzei** [comment]
Tested and work :tada:

**Comment by jprusch** [comment]
Sehr geehrte Damen und Herren,
ich bin vom 8.6. bis zum 12.6. nicht im Hause und habe daher leider keinen Zugriff auf meine E-Mails.
Ihre Mail wird NICHT weitergeleitet und nach meiner Rückkehr bearbeitet.
In dringende Fällen wenden Sie sich bitte an Hr. Tarrach (v.tarrach@schaeferbarthold.de)
Mit freundlichen Grüßen

i.V. Jan-Peter Rusch

TEL +49 (0)571-502-145 | FAX +49 (0)571-502-66-145
j.rusch@schaeferbarthold.de
______________________________________________________________________
Schäferbarthold GmbH
Erbeweg 2-12 | 32457 Porta Westfalica | Deutschland
www.schaeferbarthold.de
Schäferbarthold GmbH: Amtsgericht Bad Oeynhausen HRB 3748
Geschäftsführer: Dr. Volker Schäferbarthold, Dr. Christian Schäferbarthold, Wolfgang Schäferbarthold
Tested and work :tada:
