### ISSUE TITLE
Add function to set filename of recording on upload

### ISSUE THREAD

**Issue by jprusch** [streamer45/mattermost-plugin-screen#5]
Right now each recording is stored in a channel with filename "screenrec.mp4". As we also use the Files in Channel plugin, things get a bit messy when a couple of recordings are stored in the same channel...
Otherwise a real useful nice addon.

**Comment by streamer45** [comment]
@jprusch 

Thanks for your input. Using a hard-coded filename was indeed a simplification. 
I'll make sure to address this next time I get a chance to work on this plugin.

**Comment by streamer45** [comment]
@jprusch 

I've just published a [new release](https://github.com/streamer45/mattermost-plugin-screen/releases/tag/v0.3.0) with this feature.

**Comment by jprusch** [comment]
Perfect! Works like a charm! Thx
